FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONPATH=/app/src

WORKDIR /app

COPY pyproject.toml README.md ./
COPY src ./src

RUN pip install --upgrade pip && pip install --no-cache-dir -e .

EXPOSE 8000

CMD ["python", "src/fleetops/services/web/manage.py", "runserver", "0.0.0.0:8000", "--noreload"]
