FROM python:3.12-slim-bookworm

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONPATH=/app/src

WORKDIR /app

RUN apt-get update \
    && apt-get upgrade -y --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

COPY pyproject.toml README.md ./
COPY src ./src
COPY migrations ./migrations
COPY alembic.ini ./
COPY entrypoint.sh ./entrypoint.sh

RUN pip install --upgrade pip && pip install --no-cache-dir -e .

EXPOSE 8001

ENTRYPOINT ["sh", "./entrypoint.sh"]
