apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fleetops.fullname" . }}-credentials
  labels:
    {{- include "fleetops.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.database.name | quote }}
  POSTGRES_USER: {{ .Values.database.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.database.password | quote }}
  DJANGO_SECRET_KEY: {{ .Values.django.secretKey | quote }}
